# Generated by Django 4.2.17 on 2025-01-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invitee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inviter',
            new_name='Invitee',
        ),
    ]
