# Generated by Django 5.1.4 on 2025-01-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invitee', '0002_rename_inviter_invitee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitee',
            options={'verbose_name': 'Invitee'},
        ),
    ]
